services:
    nginx:
        build:
            context: ./docker
            dockerfile: Dockerfile-nginx
        volumes:
            - ./:/var/www/project/:cached
        ports:
            - 9000:80
        networks:
            - symfony

    fpm:
        build:
            context: ./docker/
            dockerfile: Dockerfile-php
        environment:
            - DATABASE_URL=mysql://root:root@db/docker_sf
        volumes:
            - ./:/var/www/project/:cached
        networks:
            - symfony
networks:
    symfony:
